### ISSUE TITLE
Einstellungen/Instllierte Apps... 

### ISSUE THREAD

**Issue by MaxBde** [berlinux2016/MIUI9-ger#178]
.... FC, wenn Telefon auf Deutsch. Geht, wenns auf Englisch ist. 
RedmiNote3SE KATE, weekly 7.12.1
Keine Ahnung, ob das hierher gehört, habs auch im Bugreport im Forum gemeldet. 
Log:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.miui.securitycenter/com.miui.appmanager.AppManagerMainActivity}: java.lang.ArrayIndexOutOfBoundsException: length=5; index=5
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
	at android.app.ActivityThread.access$1000(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
	at android.os.Handler.dispatchMessage(Handler.java)
	at android.os.Looper.loop(Looper.java)
	at android.app.ActivityThread.main(ActivityThread.java)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=5; index=5
	at com.miui.appmanager.AppManagerMainActivity.kf(Unknown Source)
	at com.miui.appmanager.AppManagerMainActivity.initData(Unknown Source)
	at com.miui.appmanager.AppManagerMainActivity.onCreate(Unknown Source)
	at android.app.Activity.performCreate(Activity.java)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
	... 10 more

**Comment by berlinux2016** [comment]
Kann ich hier leider nicht mit den Test Geräten reproduzieren.

**Comment by MaxBde** [comment]
Scheint nen Problem in der offiziellen Global Dev zu sein, auf der KATE basiert, im Gegensatz zu allen anderen Geräten bei Xiaomi.eu , die ja auf der China Dev basieren. Muss wohl von offizieller en.miui.com - Seite gefixt werden.

**Comment by berlinux2016** [comment]
Problem liegt an der Global Dev die demnächst auch bei kate abgelöst wird. Deshalb closed da wir hier nichts ändern können.
